### ISSUE TITLE
[envuidgid] set envs HOME & USER

### ISSUE THREAD

**Issue by steakknife** [bruceg/daemontools-encore#18]
Basically, envuidgid should setup the env to not break apps running as another user similar but lighter than sudo.  At a minimum, setting HOME and USER from `struct passwd` fields from `getpwname()`.  Not doing this most likely inherits the environment from root, which is likely bad news.

[HN discussion](https://news.ycombinator.com/item?id=7644525)

**Comment by bruceg** [comment]
This is resolved by a new setuser program in the next version.
