### ISSUE TITLE
"svc -dx" on a service does not cause the log service to stop after the main service exits

### ISSUE THREAD

**Issue by timbunce** [bruceg/daemontools-encore#19]
The Changes for daemontools-encore-1.02 says:

```
If a supervise is managing both a main and log service,
issuing "svc -dx" on the service will cause the log to stop
after the main service exits.
```

This doesn't seem to be the case.

I've a standard log/run script that does `exec multilog ...`. When I do `svc -dx foo` on the parent the multilog exits after reading eof on stdin, but the log supervise restarts it (and keeps on restarting it because the multilog exits immediately due to end on stdin).

Using strace on the multilog and the parent log supervise process I can see that the multilog exits on eof, as expected. The parent log supervise process however doesn't get told how to act. The `svc -dx foo` on the parent has no effect on the log supervise, so naturally it restarts the multilog when it exits.

**Comment by bruceg** [comment]
I think this is perhaps confusion in the documentation. One of the features daemontools-encore added was the ability to run both the service and the log from the same supervise. In that case, serivce/log would be an executable script instead of a subdirectory containing service/log/run.
