### ISSUE TITLE
"svc -d . ; svc -u ." doesn't restart a service if the service doesn't exit quickly

### ISSUE THREAD

**Issue by josb** [bruceg/daemontools-encore#20]
In some wrapper scripts I had to replace "svc -d .; svc -u ." with "svc -t ." since bringing a certain kind of service down and then up when the run script hasn't exited yet causes the up to be ignored.
The issue seems to be that supervise thinks it's in start mode (firstrun == 1)
and doesn't restart the service if it exited > 0.
Specifically, in supervise.c the following condition is triggered:

firstrun == 1 and wait_crashed(wstat) == 15

```
  if ((firstrun && (wait_crashed(wstat) || wait_exitcode(wstat) != 0))
|| (!wait_crashed(wstat) && wait_exitcode(wstat) == 100)) {
          svc->flagwantup = 0;
          svc->flagstatus = svstatus_failed;
  }
```

Repro: create a service which doesn't exit right away when running 'svc -d .; svc -u .';
svstat will show 'failed' in the status message, and the service will be left down.

The underlying problem seems to be that firstrun is set when it should not (it
should only be set if the start file exists). Maybe the following assignment
in handling 'u' in doit is wrong:

```
        firstrun = !svcmain.flagwantup;
```

**Comment by bruceg** [comment]
As far as I can tell, this was fixed by pull #56. I am having difficulty producing a repeatable test case for this though.
